<?php if(!defined("CONF_PATH")) { die("No direct script access allowed."); } 

Database::initRoot();

// Create the Site's Official Hashtags
ContentHashtags::create("Sports", "Sports");
ContentHashtags::create("Football", "Football");
ContentHashtags::create("NFL", "National Football League");
ContentHashtags::create("AFC", "American Football Conference");
ContentHashtags::create("BALRavens", "Baltimore Ravens");
ContentHashtags::create("BUFBills", "Buffalo Bills");
ContentHashtags::create("CINBengals", "Cincinnati Bengals");
ContentHashtags::create("CLEBrowns", "Cleveland Browns");
ContentHashtags::create("DENBroncos", "Denver Broncos");
ContentHashtags::create("HOUTexans", "Houston Texans");
ContentHashtags::create("INDColts", "Indianapolis Colts");
ContentHashtags::create("JAXJaguars", "Jacksonville Jaguars");
ContentHashtags::create("KCChiefs", "Kansas City Chiefs");
ContentHashtags::create("MIADolphins", "Miami Dolphins");
ContentHashtags::create("NEPatriots", "New England Patriots");
ContentHashtags::create("NYJets", "New York Jets");
ContentHashtags::create("OAKRaiders", "Oakland Raiders");
ContentHashtags::create("PITTSteelers", "Pittsburgh Steelers");
ContentHashtags::create("SDChargers", "San Diego Chargers");
ContentHashtags::create("TENNTitans", "Tennessee Titans");
ContentHashtags::create("NFC", "National Football Conference");
ContentHashtags::create("AZCardinals", "Arizona Cardinals");
ContentHashtags::create("ATLFalcons", "Atlanta Falcons");
ContentHashtags::create("CARPanthers", "Carolina Panthers");
ContentHashtags::create("CHIBears", "Chicago Bears");
ContentHashtags::create("DALCowboys", "Dallas Cowboys");
ContentHashtags::create("DETLions", "Detroit Lions");
ContentHashtags::create("GBPackers", "Green Bay Packers");
ContentHashtags::create("MNVikings", "Minnesota Vikings");
ContentHashtags::create("NOLASaints", "New Orleans Saints");
ContentHashtags::create("NYGiants", "NY Giants");
ContentHashtags::create("PHIEagles", "Philadelphia Eagles");
ContentHashtags::create("SF49ers", "San Francisco 49ers");
ContentHashtags::create("SEASeahawks", "Seattle Seahawks");
ContentHashtags::create("STLRams", "St. Louis Rams");
ContentHashtags::create("TBBuccaneers", "Tampa Bay Buccaneers");
ContentHashtags::create("WASRedskins", "Washington Redskins");

// Create the Site's Search Filters
ModuleSearch::createFilterOption("search-home", "Teams", "BALRavens", "Baltimore Ravens", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "BUFBills", "Buffalo Bills", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "CINBengals", "Cincinnati Bengals", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "CLEBrowns", "Cleveland Browns", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "DENBroncos", "Denver Broncos", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "HOUTexans", "Houston Texans", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "INDColts", "Indianapolis Colts", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "JAXJaguars", "Jacksonville Jaguars", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "KCChiefs", "Kansas City Chiefs", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "MIADolphins", "Miami Dolphins", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "NEPatriots", "New England Patriots", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "NYJets", "New York Jets", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "OAKRaiders", "Oakland Raiders", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "PITTSteelers", "Pittsburgh Steelers", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "SDChargers", "San Diego Chargers", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "TENNTitans", "Tennessee Titans", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "AZCardinals", "Arizona Cardinals", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "ATLFalcons", "Atlanta Falcons", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "CARPanthers", "Carolina Panthers", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "CHIBears", "Chicago Bears", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "DALCowboys", "Dallas Cowboys", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "DETLions", "Detroit Lions", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "GBPackers", "Green Bay Packers", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "MNVikings", "Minnesota Vikings", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "NOLASaints", "New Orleans Saints", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "NYGiants", "NY Giants", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "PHIEagles", "Philadelphia Eagles", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "SF49ers", "San Francisco 49ers", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "SEASeahawks", "Seattle Seahawks", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "STLRams", "St. Louis Rams", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "TBBuccaneers", "Tampa Bay Buccaneers", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Teams", "WASRedskins", "Washington Redskins", ModuleSearch::FILTER_SINGLE);