<?php if(!defined("CONF_PATH")) { die("No direct script access allowed."); } 

Database::initRoot();

// Create the Site's Official Hashtags
ContentHashtags::create("Sports", "Sports");
ContentHashtags::create("Basketball", "Basketball");
ContentHashtags::create("NCAAM", "NCAA Men's Basketball");
ContentHashtags::create("AACBasketball", "AAC Basketball");
ContentHashtags::create("UCBearcatsBB", "Cincinnati Bearcats Basketball");
ContentHashtags::create("UConnBB", "Connecticut Huskies Basketball");
ContentHashtags::create("ECUPiratesBB", "East Caorlina Pirates Basketball");
ContentHashtags::create("HOUCougarsBB", "Houston Cougars Basketball");
ContentHashtags::create("MEMTigersBB", "Memphis Tigers Basketball");
ContentHashtags::create("SMUMustangsBB", "SMU Mustangs Basketball");
ContentHashtags::create("USFBullsBB", "South Florida Bulls Basketball");
ContentHashtags::create("TempleBB", "Temple Owls Basketball");
ContentHashtags::create("TulaneBB", "Tulane Green Wave Basketball");
ContentHashtags::create("TulsaBB", "Tulsa Golden Hurricanes Basketball");
ContentHashtags::create("UCFKnightsBB", "UCF Knights Basketball");
ContentHashtags::create("ACCBasketball", "ACC Basketball");
ContentHashtags::create("BCEaglesBB", "Boston College Eagles Basketball");
ContentHashtags::create("ClemsonBB", "Clemson Tigers Basketball");
ContentHashtags::create("DukeBB", "Duke Blue Devils Basketball");
ContentHashtags::create("SeminoleBB", "Florida State Seminoles Basketball");
ContentHashtags::create("GATechBB", "Georgia Tech Yellow Jackets Basketball");
ContentHashtags::create("LouisvilleBB", "Louisville Cardinals Basketball");
ContentHashtags::create("UMiamiBB", "Miami Hurricanes Basketball");
ContentHashtags::create("TarHeelsBB", "North Carolina Tar Heels Basketball");
ContentHashtags::create("NCStateBB", "North Carolina State Wolfpack Basketball");
ContentHashtags::create("NotreDameBB", "Notre Dame Fighting Irish Basketball");
ContentHashtags::create("PittPantherBB", "Pittsburgh Panthers Basketball");
ContentHashtags::create("SyracuseBB", "Syracuse Orange Basketball");
ContentHashtags::create("UVCavaliersBB", "Virginia Cavaliers Basketball");
ContentHashtags::create("HokiesBB", "Virginia Tech Hokies Basketball");
ContentHashtags::create("WakeForestBB", "Wake Forest Demon Deacons Basketball");
ContentHashtags::create("AmericaEastBasketball", "America East Basketball");
ContentHashtags::create("AlbanyBB", "Albany Great Danes Basketball");
ContentHashtags::create("BinghamtonBB", "Binghamton Bearcats Basketball");
ContentHashtags::create("HartfordHawkBB", "Hartford Hawks Basketball");
ContentHashtags::create("MaineBB", "Maine Blackbears Basketball");
ContentHashtags::create("NHWildcatsBB", "New Hampshire Wildcats Basketball");
ContentHashtags::create("StoneyBrookSeawolves", "Stony Brook Seawolves Basketball");
ContentHashtags::create("RiverHawksBB", "UMass Lowell River Hawks Basketball");
ContentHashtags::create("UMBCRetrieversBB", "UMBC Retrievers Basketball");
ContentHashtags::create("VermontBB", "Vermont Catamounts Basketball");
ContentHashtags::create("AtlanticSunBasketball", "Atlantic Sun Basketball");
ContentHashtags::create("FGCEaglesBB", "Florida Gulf Coast Eagles Basketball");
ContentHashtags::create("JacksonvilleBB", "Jacksonville Dolphins Basketball");
ContentHashtags::create("KennesawBB", "Kennesaw State Owls Basketball");
ContentHashtags::create("LipscombBB", "Lipscomb Bisons Basketball");
ContentHashtags::create("NFloridaBB", "North Florida Ospreys Basketball");
ContentHashtags::create("NKentuckyBB", "Northern Kentucky Norse Basketball");
ContentHashtags::create("StetsonBB", "Stetson Hatters Basketball");
ContentHashtags::create("UpstateBB", "USC Upstate Spartans Basketball");
ContentHashtags::create("Atlantic10Basketball", "Atlantic 10 Basketball");
ContentHashtags::create("DavidsonBB", "Davidson Wildcats Basketball");
ContentHashtags::create("DaytonBB", "Dayton Fliers Basketball");
ContentHashtags::create("DuquesneBB", "Duquesne Dukes Basketball");
ContentHashtags::create("FordhamBB", "Fordham Rams Basketball");
ContentHashtags::create("GeorgeMasonBB", "George Mason Patriots Basketball");
ContentHashtags::create("GeorgeWashBB", "George Washington Colonials Basketball");
ContentHashtags::create("LaSalleBB", "La Salle Explorers Basketball");
ContentHashtags::create("UMassBB", "Massachusetts Minutemen Basketball");
ContentHashtags::create("RhodeIslandBB", "Rhode Island Rams Basketball");
ContentHashtags::create("SpidersBB", "Richmond Spiders Basketball");
ContentHashtags::create("StJoeBB", "Saint Joseph's Hawks Basketball");
ContentHashtags::create("BillikensBB", "Saint Louis Billikens Basketball");
ContentHashtags::create("BonniesBB", "St. Bonaventure Bonnies Basketball");
ContentHashtags::create("VCURamsBB", "Virginia Commonwealth Rams Basketball");
ContentHashtags::create("Big12Basketball", "Big 12 Basketball");
ContentHashtags::create("BaylorBB", "Baylor Bears Basketball");
ContentHashtags::create("IowaStBB", "Iowa State Cyclones Basketball");
ContentHashtags::create("KansasBB", "Kansas Jayhawks Basketball");
ContentHashtags::create("KStateBB", "Kansas State Wildcats Basketball");
ContentHashtags::create("SoonersBB", "Oklahoma Sooners Basketball");
ContentHashtags::create("OKStateBB", "Oklahoma State Cowboys Basketball");
ContentHashtags::create("HornedFrogsBB", "TCU Horned Frogs Basketball");
ContentHashtags::create("TexasBB", "Texas Longhorns Basketball");
ContentHashtags::create("TexasTechBB", "Texas Tech Red Raiders Basketball");
ContentHashtags::create("WestVirginiaBB", "West Virginia Mountaineers Basketball");
ContentHashtags::create("BigEastBasketball", "Big East Basketball");
ContentHashtags::create("ButlerBB", "Butler Bulldogs Basketball");
ContentHashtags::create("CreightonBB", "Creighton Bluejays Basketball");
ContentHashtags::create("DePaulBB", "DePaul Blue Demons Basketball");
ContentHashtags::create("HoyasBB", "Georgetown Hoyas Basketball");
ContentHashtags::create("MarquetteBB", "Marquette Golden Eagles Basketball");
ContentHashtags::create("ProvidenceBB", "Providence Friars Basketball");
ContentHashtags::create("StJohnsBB", "St. John's Red Storm Basketball");
ContentHashtags::create("SetonHallBB", "Seton Hall Pirates Basketball");
ContentHashtags::create("VillanovaBB", "Villanova Wildcats Basketball");
ContentHashtags::create("XavierBB", "Xavier Musketeers Basketball");
ContentHashtags::create("BigSkyBasketball", "Big Sky Basketball");
ContentHashtags::create("EWEaglesBB", "Eastern Washington Eagle Basketball");
ContentHashtags::create("IdahoStBB", "Idaho State Vandals Basketball");
ContentHashtags::create("MontantBB", "Montana Grizzlies Basketball");
ContentHashtags::create("MontantStBB", "Montana State Bobcats Basketball");
ContentHashtags::create("NDakotaBB", "North Dakota Basketball");
ContentHashtags::create("NArizonaBB", "Northern Arizona Lumberjacks Basketball");
ContentHashtags::create("NColoradoBB", "Northern Colorado Bears Basketball");
ContentHashtags::create("PortlandStBB", "Portland State Vikings Basketball");
ContentHashtags::create("SacStBB", "Sacramento State Hornets Basketball");
ContentHashtags::create("SUtahBB", "Southern Utah Thunderbirds Basketball");
ContentHashtags::create("WeberStBB", "Weber State Wildcats Basketball");
ContentHashtags::create("BigSouthBasketball", "Big South Basketball");
ContentHashtags::create("CampbellBB", "Campbell Fighting Camels Basketball");
ContentHashtags::create("ChalestonSouthernBB", "Charleston Southern Buccaneers Basketball");
ContentHashtags::create("ChanticleersBB", "Coastal Carolina Chanticleers Basketball");
ContentHashtags::create("GardnerWebbBB", "Gardner-Webb Runnin' Bulldogs Basketball");
ContentHashtags::create("HighPointBB", "High Point Panthers Basketball");
ContentHashtags::create("LibertyBB", "Liberty Flames Basketball");
ContentHashtags::create("LongwoodBB", "Longwood Lancers Basketball");
ContentHashtags::create("UNCAshevilleBB", "UNC Asheville Bulldogs Basketball");
ContentHashtags::create("BlueHoseBB", "Presbyterian Blue Hose Basketball");
ContentHashtags::create("RadfordBB", "Radford Highlanders Basketball");
ContentHashtags::create("WinthropBB", "Winthrop Eagles Basketball");
ContentHashtags::create("BigTenBasketball", "Big Ten Basketball");
ContentHashtags::create("IllinoisBB", "Illinois Fighting Illini Basketball");
ContentHashtags::create("IndianaBB", "Indiana Hoosiers Basketball");
ContentHashtags::create("IowaBB", "Iowa Hawkeyes Basketball");
ContentHashtags::create("MarylandBB", "Maryland Terrapins Basketball");
ContentHashtags::create("MichiganBB", "Michigan Wolverines Basketball");
ContentHashtags::create("MichStateBB", "Michigan State Spartans Basketball");
ContentHashtags::create("MinnesotaBB", "Minnesota Golden Gophers Basketball");
ContentHashtags::create("NebraskaBB", "Nebraska Cornhuskers Basketball");
ContentHashtags::create("NWWildcatsBB", "Northwester Wildcats Basketball");
ContentHashtags::create("OhioStBB", "Ohio State Buckeyes Basketball");
ContentHashtags::create("PennStateBB", "Penn State Nittany Lions Basketball");
ContentHashtags::create("PurdueBB", "Purdue Boilermakers Basketball");
ContentHashtags::create("RutgersBB", "Rutgers Scarlet Knights Basketball");
ContentHashtags::create("WisconsinBB", "Wisconsin Badgers Basketball");
ContentHashtags::create("BigWestBasketball", "Big West Basketball");
ContentHashtags::create("CalPolyBB", "Cal Poly Mustangs Basketball");
ContentHashtags::create("CalStFullertonBB", "Cal State Fullerton Titans Basketball");
ContentHashtags::create("MatadorsBB", "Cal State Northridge Matadors Basketball");
ContentHashtags::create("HawaiiBB", "Hawaii Rainbow Warriors Basketball");
ContentHashtags::create("CSLB49ersBB", "Long Beach State 49ers Basketball");
ContentHashtags::create("UCDavisBB", "UC Davis Aggies Basketball");
ContentHashtags::create("UCIrvineBB", "UC Irvine Anteaters Basketball");
ContentHashtags::create("UCRiversideBB", "UC Riverside Highlanders Basketball");
ContentHashtags::create("GauchosBB", "UC Santa Barbara Gauchos Basketball");
ContentHashtags::create("ColonialBasketball", "Colonial Basketball");
ContentHashtags::create("CharlestonBB", "Charleston Cougars Basketball");
ContentHashtags::create("DelawareBB", "Delaware Fightin' Blue Hens Basketball");
ContentHashtags::create("DrexelBB", "Drexel Dragons Basketball");
ContentHashtags::create("ElonBB", "Elon Phoenix Basketball");
ContentHashtags::create("HofstraBB", "Hofstra Pride Basketball");
ContentHashtags::create("JamesMadisonBB", "James Madison Dukes Basketball");
ContentHashtags::create("NEHuskiesBB", "Northeastern Huskies Basketball");
ContentHashtags::create("NCWilmingtonBB", "North Carolina-Wilmington Seahawks Basketball");
ContentHashtags::create("TowsonBB", "Towson Tigers Basketball");
ContentHashtags::create("TribeBB", "Williams & Mary Tribe Basketball");
ContentHashtags::create("ConferenceUSABasketball", "Conference USA Basketball");
ContentHashtags::create("Charlotte49ersBB", "Charlette 49ers Basketball");
ContentHashtags::create("FAUOwlsBB", "Florida Atlantic Owls Basketball");
ContentHashtags::create("FIUPanthersBB", "Florida International Panthers Basketball");
ContentHashtags::create("LATechBB", "Louisiana Tech Bulldogs Basketball");
ContentHashtags::create("MarshallBB", "Marshall Thundering Herd Basketball");
ContentHashtags::create("BlueRaidersBB", "Middle Tennessee Blue Raiders Basketball");
ContentHashtags::create("MeanGreenBB", "North Texas Mean Green Basketball");
ContentHashtags::create("OldDominionBB", "Old Dominion Monarchs Basketball");
ContentHashtags::create("RiceBB", "Rice Owls Basketball");
ContentHashtags::create("SouthernMissBB", "Southern Miss Golden Eagles Basketball");
ContentHashtags::create("UABBlazersBB", "UAB Blazers Basketball");
ContentHashtags::create("UTEPMinersBB", "UTEP Miners Basketball");
ContentHashtags::create("UTSARoadrunnersBB", "UTSA Roadrunners Basketball");
ContentHashtags::create("HilltoppersBB", "Western Kentucky Hilltoppers Basketball");
ContentHashtags::create("HorizonLeagueBasketball", "Horizon League Basketball");
ContentHashtags::create("CLEStBB", "Cleveland State Vikings Basketball");
ContentHashtags::create("DETTitansBB", "Detroit Titans Basketball");
ContentHashtags::create("GBPhoenixBB", "Green Bay Phoenix Basketball");
ContentHashtags::create("ILChicagoFlamesBB", "Illinois-Chicago Flames Basketball");
ContentHashtags::create("MKEPanthersBB", "Milwaukee Panthers Basketball");
ContentHashtags::create("GoldenGrizzliesBB", "Oakland Golden Grizzlies Basketball");
ContentHashtags::create("ValparaisoBB", "Valparaiso Crusaders Basketball");
ContentHashtags::create("WrightStBB", "Wright State Raiders Basketball");
ContentHashtags::create("YoungstownStBB", "Youngstown State Penguins Basketball");
ContentHashtags::create("IndependentBasketball", "Independent Basketball");
ContentHashtags::create("NJITHighlandersBB", "NJIT Highlanders Basketball");
ContentHashtags::create("IvyLeagueBasketball", "Ivy League Basketball");
ContentHashtags::create("BrownBB", "Brown Bears Basketball");
ContentHashtags::create("ColumbiaBB", "Columbia Lions Basketball");
ContentHashtags::create("CornellBB", "Cornell Big Red Basketball");
ContentHashtags::create("DartmouthBB", "Dartmouth Big Green Basketball");
ContentHashtags::create("HarvardBB", "Harvard Crimson Basketball");
ContentHashtags::create("PennQuakersBB", "Pennsylvania Quakers Basketball");
ContentHashtags::create("PrincetonBB", "Princeton Tigers Basketball");
ContentHashtags::create("YaleBB", "Yale Bulldogs Basketball");
ContentHashtags::create("MAACBasketball", "MAAC Basketball");
ContentHashtags::create("CanisiusBB", "Canisius Golden Griffins Basketball");
ContentHashtags::create("FairfieldBB", "Fairfield Stags Basketball");
ContentHashtags::create("IonaBB", "Iona Gaels Basketball");
ContentHashtags::create("ManhattanBB", "Manhattan Jaspers Basketball");
ContentHashtags::create("MaristBB", "Marist Red Foxes Basketball");
ContentHashtags::create("MonmouthBB", "Monmouth Hawks Basketball");
ContentHashtags::create("NiagaraBB", "Niagara Purple Eagles Basketball");
ContentHashtags::create("QuinnipiacBB", "Quinnipiac Bobcats Basketball");
ContentHashtags::create("RidersBB", "Riders Broncs Basketball");
ContentHashtags::create("SienaBB", "Siena Saints Basketball");
ContentHashtags::create("StPetersBB", "St. Peter's Peacocks Basketball");
ContentHashtags::create("MACBasketball", "MAC Basketball");
ContentHashtags::create("AkronBB", "Akron Zips Basketball");
ContentHashtags::create("BallStBB", "Ball State Cardinals Basketball");
ContentHashtags::create("BowlingGreenBB", "Bowling Green Falcons Basketball");
ContentHashtags::create("BuffaloBB", "Buffalo Bulls Basketball");
ContentHashtags::create("CMUChipsBB", "Central Michigan Chippewas Basketball");
ContentHashtags::create("EMUEaglesBB", "Eastern Micigan Eagles Basketball");
ContentHashtags::create("KentStBB", "Kent State Golden Flashes Basketball");
ContentHashtags::create("MiamiOhioBB", "Miami (OH) Redhawks Basketball");
ContentHashtags::create("NIUHuskiesBB", "Northern Illinois Huskies Basketball");
ContentHashtags::create("OhioBB", "Ohio Bobcats Basketball");
ContentHashtags::create("ToledoBB", "Toledo Rockets Basketball");
ContentHashtags::create("WMUBroncosBB", "Western Michigan Broncos Basketball");
ContentHashtags::create("MEACBasketball", "MEAC Basketball");
ContentHashtags::create("BethuneCookmanBB", "Bethune-Cookman Wildcats Basketball");
ContentHashtags::create("CoppinBB", "Coppin State Eagles Basketball");
ContentHashtags::create("DelawareStBB", "Delaware State Hornets Basketball");
ContentHashtags::create("RattlersBB", "Florida A&M Rattlers Basketball");
ContentHashtags::create("HamptonBB", "Hampton Pirates Basketball");
ContentHashtags::create("HowardBB", "Howard Bison Basketball");
ContentHashtags::create("ShoreHawksBB", "Maryland-Eastern Shore Hawks Basketball");
ContentHashtags::create("MorganStBB", "Morgan State Bears Basketball");
ContentHashtags::create("NorfolkStBB", "Norfolk State Spartans Basketball");
ContentHashtags::create("NCATAggiesBB", "North Carolina A&T Aggies Basketball");
ContentHashtags::create("NCCEaglesBB", "North Carolina Central Eagles Basketball");
ContentHashtags::create("SavannahStBB", "Savannah State Tigers Basketball");
ContentHashtags::create("SCStBB", "South Carolina State Bulldogs Basketball");
ContentHashtags::create("MissouriValleyBasketball", "Missouri State Basketball");
ContentHashtags::create("BradleyBB", "Bradley Braves Basketball");
ContentHashtags::create("DrakeBB", "Drake Bulldogs Basketball");
ContentHashtags::create("EvansvilleBB", "Evansville Purple Aces Basketball");
ContentHashtags::create("RedbirdsBB", "Illinois State Redbirds Basketball");
ContentHashtags::create("SycamoresBB", "Indiana State Sycamores Basketball");
ContentHashtags::create("RamblersBB", "Loyola (IL) Ramblers Basketball");
ContentHashtags::create("MissouriStBB", "Missouri State Bears Basketball");
ContentHashtags::create("NorthernIowaBB", "Northern Iowa Panthers Basketball");
ContentHashtags::create("SalukisBB", "Southern Illinois Salukis Basketball");
ContentHashtags::create("ShockersBB", "Wichita State Shockers Basketball");
ContentHashtags::create("MountainWestBasketball", "Mountain West Basketball");
ContentHashtags::create("AirForceBB", "Air Force Falcons Basketball");
ContentHashtags::create("BoiseStBB", "Boise State Broncos Basketball");
ContentHashtags::create("ColoradoStBB", "Colorado State Rams Basketball");
ContentHashtags::create("FresnoBB", "Fresno State Bulldogs Basketball");
ContentHashtags::create("NevadaBB", "Nevada Wolf Pack Basketball");
ContentHashtags::create("NewMexicoBB", "New Mexico Lobos Basketball");
ContentHashtags::create("SanDiegoStBB", "San Diego State Aztecs Basketball");
ContentHashtags::create("SanJoseStBB", "San Jose State Spartans Basketball");
ContentHashtags::create("UNLVRebelsBB", "UNLV Rebels Basketball");
ContentHashtags::create("UtahStBB", "Utah State Aggies Basketball");
ContentHashtags::create("WyomingBB", "Wyoming Cowboys Basketball");
ContentHashtags::create("NortheastBasketball", "Northeast Basketball");
ContentHashtags::create("BryantBB", "Bryant Bulldogs Basketball");
ContentHashtags::create("CCSBlueDevilsBB", "Central Connecticut State Blue Devils Basketball");
ContentHashtags::create("FairleighDickinsonBB", "Fairleigh Dickinson Knights Basketball");
ContentHashtags::create("BlackbirdsBB", "LIU Brooklyn Blackbirds Basketball");
ContentHashtags::create("MountStMarysBB", "Mount St. Mary's Mountaineers Basketball");
ContentHashtags::create("RobertMorrisBB", "Robert Morris Colonials Basketball");
ContentHashtags::create("SacredHeartBB", "Sacred Heart Pioneers Basketball");
ContentHashtags::create("StFrancisTerriersBB", "St. Francis (NY) Terriers Basketball");
ContentHashtags::create("RedFlashBB", "St. Francis U The Red Flash Basketball");
ContentHashtags::create("WagnerBB", "Wagner Seahawks Basketball");
ContentHashtags::create("OhioValleyBasketball", "Ohio Valley Basketball");
ContentHashtags::create("AustinPeayStBB", "Austin Peay State Governors Basketball");
ContentHashtags::create("BelmontBB", "Belmont Bruins Basketball");
ContentHashtags::create("EasternIllinoisBB", "Eastern Illinois Panthers Basketball");
ContentHashtags::create("EasternKentuckyBB", "Eastern Kentucky Colonels Basketball");
ContentHashtags::create("JacksonvilleStBB", "Jacksonville State Gamecocks Basketball");
ContentHashtags::create("MoreheadStBB", "Morehead State Eagles Basketball");
ContentHashtags::create("MurrayStBB", "Murray State Racers Basketball");
ContentHashtags::create("SEMissouriStBB", "Southeast Missouri State Redhawks Basketball");
ContentHashtags::create("SIUEdwardsvilleBB", "SIU-Edwardsville Cougars Basketball");
ContentHashtags::create("TNMartinBB", "Tennessee-Martin Skyhawks Basketball");
ContentHashtags::create("TNStBB", "Tennessee State Tigers Basketball");
ContentHashtags::create("TNTechBB", "Tennessee Tech Golden Eagles Basketball");
ContentHashtags::create("Pac12Basketball", "Pac-12 Basketball");
ContentHashtags::create("ArizonaBB", "Arizona Wildcats Basketball");
ContentHashtags::create("ArizonStBB", "Arizona State Sun Devils Basketball");
ContentHashtags::create("CalBearsBB", "Calirfornia Bears Basketball");
ContentHashtags::create("ColoradoBB", "Colorado Buffaloes Basketball");
ContentHashtags::create("OreganBB", "Oregon Ducks Basketball");
ContentHashtags::create("OregonStBB", "Oregon State Beavers Basketball");
ContentHashtags::create("StanfordBB", "Stanford Cardinal Basketball");
ContentHashtags::create("UCLABruinsBB", "UCLA Bruins Basketball");
ContentHashtags::create("TrojansBB", "USC Trojans Basketball");
ContentHashtags::create("UtahBB", "Utah Utes Basketball");
ContentHashtags::create("WashingtonBB", "Washington Huskies Basketball");
ContentHashtags::create("WashingtonStBB", "Washington State Cougars Basketball");
ContentHashtags::create("PatriotLeagueBasketball", "Patriot League Basketball");
ContentHashtags::create("AmericanBB", "American University Eagles Basketball");
ContentHashtags::create("ArmyBB", "Army Black Knights Basketball");
ContentHashtags::create("BostonUTerriersBB", "Boston University Terriers Basketball");
ContentHashtags::create("BucknellBB", "Bucknell Bison Basketball");
ContentHashtags::create("ColgateBB", "Colgate Raiders Basketball");
ContentHashtags::create("HolyCrossBB", "Holy Cross Crusaders Basketball");
ContentHashtags::create("LafayetteBB", "Lafayette Leopards Basketball");
ContentHashtags::create("LehighBB", "Lehigh Mountain Hawks Basketball");
ContentHashtags::create("GreyhoundsBB", "Loyola (MD) Greyhounds Basketball");
ContentHashtags::create("NavyBB", "Navy Midshipmen Basketball");
ContentHashtags::create("SECBasketball", "SEC Basketball");
ContentHashtags::create("AlabamaBB", "Alabama Crimson Tide Basketball");
ContentHashtags::create("ArkansasBB", "Arkansas Razorbacks Basketball");
ContentHashtags::create("AuburnBB", "Auburn Tigers Basketball");
ContentHashtags::create("FloridaBB", "Florida Gators Basketball");
ContentHashtags::create("GeorgiaBB", "Georgia Bulldogs Basketball");
ContentHashtags::create("KentuckyBB", "Kentucky Wildcats Basketball");
ContentHashtags::create("LSUTigersBB", "LSU Tigers Basketball");
ContentHashtags::create("OleMissBB", "Mississippi Rebels Basketball");
ContentHashtags::create("MudDogsBB", "Mississippi State Mud Dogs Basketball");
ContentHashtags::create("MissouriBB", "Missouri Tigers Basketball");
ContentHashtags::create("SouthCarolinaBB", "South Carolina Gamecocks Basketball");
ContentHashtags::create("TennesseeBB", "Tennessee Volunteers Basketball");
ContentHashtags::create("AggiesBB", "Texas A&M Aggies Basketball");
ContentHashtags::create("VanderbiltBB", "Vanderbilt Commodores Basketball");
ContentHashtags::create("SouthernBasketball", "Southern Basketball");
ContentHashtags::create("ChattanoogaBB", "Chattanooga Mocs Basketball");
ContentHashtags::create("CitadelBB", "Citadel Bulldogs Basketball");
ContentHashtags::create("ETennStBB", "East Tennessee State Buccaneers Basketball");
ContentHashtags::create("FurmanBB", "Furman Paladins Basketball");
ContentHashtags::create("MercerBB", "Mercer Bears Basketball");
ContentHashtags::create("SamfordBB", "Samford Bulldogs Basketball");
ContentHashtags::create("UNCGreensboroBB", "UNC Greensboro Spartans Basketball");
ContentHashtags::create("KeydetsBB", "VMI Keydets Basketball");
ContentHashtags::create("WCCatamountsBB", "Western Carolina Catamounts Basketball");
ContentHashtags::create("WoffordBB", "Wofford Terriers Basketball");
ContentHashtags::create("SouthlandBasketball", "Southland Basketball");
ContentHashtags::create("AbileneChristianBB", "Abilene Christian Wildcats Basketball");
ContentHashtags::create("CentralArkBB", "Central Arkansas Bears Basketball");
ContentHashtags::create("HoustonBaptistBB", "Houston Baptist Huskies Basketball");
ContentHashtags::create("IncarnateWordBB", "Incarnate Word Cardinals Basketball");
ContentHashtags::create("LamarBB", "Lamar Cardinals Basketball");
ContentHashtags::create("McNeeseStBB", "McNeese State Cowboys Basketball");
ContentHashtags::create("NewOrleansBB", "New Orleans Privateers Basketball");
ContentHashtags::create("NichollsStBB", "Nicholls State Colonels Basketball");
ContentHashtags::create("NWStateBB", "Northwestern State Demons Basketball");
ContentHashtags::create("SamHoustonStBB", "Sam Houston State Bearkats Basketball");
ContentHashtags::create("SELouisianaBB", "Southeastern Louisiana Lions Basketball");
ContentHashtags::create("SFALumberjacksBB", "Stephen F. Austin Lumberjacks Basketball");
ContentHashtags::create("TexasAMCCIslandersBB", "Texas A&M-CC Islanders Basketball");
ContentHashtags::create("SWACBasketball", "SWAC Basketball");
ContentHashtags::create("AlabamaAMBulldogsBB", "Alabama A&M Bulldogs Basketball");
ContentHashtags::create("AlabamaStBB", "Alabama State Hornets Basketball");
ContentHashtags::create("AlcornStBB", "Alcorn State Braves Basketball");
ContentHashtags::create("ArkPinesBluffBB", "Arkansas-Pines Bluff Golden Lions Basketball");
ContentHashtags::create("GramblingStBB", "Grambling State Tigers Basketball");
ContentHashtags::create("JacksonStBB", "Jackson State Tigers Basketball");
ContentHashtags::create("DeltaDevilsBB", "Mississippi Valle State Delta Devils Basketball");
ContentHashtags::create("PraireViewAMPanthersBB", "Prairie View A&M Panthers Basketball");
ContentHashtags::create("SouthernBB", "Southern University Jaguars Basketball");
ContentHashtags::create("TexasSouthernBB", "Texas Southern Tigers Basketball");
ContentHashtags::create("SummitLeagueBasketball", "Summit League Basketball");
ContentHashtags::create("DenverBB", "Denver Pioneers Basketball");
ContentHashtags::create("MastodonsBB", "IUPU-Fort Wayne Mastodons Basketball");
ContentHashtags::create("IUPUIndianapolisBB", "IUPU-Indianapolis Jaguars Basketball");
ContentHashtags::create("NebraskaOmahaBB", "Nebraska-Omaha Mavericks Basketball");
ContentHashtags::create("NDSUBisonBB", "North Dakota State Bison Basketball");
ContentHashtags::create("OralRobertsBB", "Oral Roberts Golden Eagles Basketball");
ContentHashtags::create("SDCoyotesBB", "South Dakota Coyotes Basketball");
ContentHashtags::create("JackrabbitsBB", "South Dakota State Jackrabbits Basketball");
ContentHashtags::create("LeathernecksBB", "Western Illinois Leathernecks Basketball");
ContentHashtags::create("SunBeltBasketball", "Sun Belt Basketball");
ContentHashtags::create("AppStBB", "Appalachian State Mountaineers Basketball");
ContentHashtags::create("ArkStBB", "Arkansas State Red Wolves Basketball");
ContentHashtags::create("GASouthernBB", "Georgia Southern Eagles Basketball");
ContentHashtags::create("GAStBB", "Georgia State Panthers Basketball");
ContentHashtags::create("IdahoBB", "Idaho Vandals Basketball");
ContentHashtags::create("RaginCajunsBB", "Louisiana-Lafayette Ragin' Cajuns Basketball");
ContentHashtags::create("WarhawksBB", "Louisiana-Monroe Warhawks Basketball");
ContentHashtags::create("NMStBB", "New Mexico State Aggies Basketball");
ContentHashtags::create("SouthAlabamaBB", "South Alabama Jaguars Basketball");
ContentHashtags::create("TexasStBB", "Texas State Bobcats Basketball");
ContentHashtags::create("TroyBB", "Troy Trojans Basketball");
ContentHashtags::create("WestCoastBasketball", "West Coast Basketball");
ContentHashtags::create("BYUCougarBB", "Brigham Young Cougars Basketball");
ContentHashtags::create("GonzagaBB", "Gonzaga Bulldogs Basketball");
ContentHashtags::create("LoyolaMarymountBB", "Loyola Marymount Lions Basketball");
ContentHashtags::create("PacificBB", "Pacific Tigers Basketball");
ContentHashtags::create("PepperdineBB", "Pepperdine Waves Basketball");
ContentHashtags::create("PortlandBB", "Portland Pilots Basketball");
ContentHashtags::create("StMarysBB", "Saint Mary's Gaels Basketball");
ContentHashtags::create("SanDiegoBB", "San Diego Toreros Basketball");
ContentHashtags::create("SanFranciscoBB", "San Francisco Dons Basketball");
ContentHashtags::create("SantaClaraBB", "Santa Clara Broncos Basketball");
ContentHashtags::create("WACBasketball", "WAC Basketball");
ContentHashtags::create("CSBRoadrunnersBB", "Cal State Bakersfield Roadrunners Basketball");
ContentHashtags::create("ChicagoStBB", "Chicago State Cougars Basketball");
ContentHashtags::create("AntelopesBB", "Grand Canyon Antelopes Basketball");
ContentHashtags::create("NMStAggiesBB", "New Mexico State Aggies Basketball");
ContentHashtags::create("SeattleBB", "Seattle Redhawks Basketball");
ContentHashtags::create("TexasPanAmBB", "Texas-Pan American Broncs Basketball");
ContentHashtags::create("KangaroosBB", "UMKC Kangaroos Basketball");
ContentHashtags::create("UtahValleyBB", "Utah Valley Wolverines Basketball");