<?php if(!defined("CONF_PATH")) { die("No direct script access allowed."); } 

Database::initRoot();

// Create the Site's Official Hashtags
ContentHashtags::create("Recipes", "Recipes");
ContentHashtags::create("PopularRecipes", "Popular Recipes");
ContentHashtags::create("GlutenFreeRecipes", "Gluten-Free Recipes");
ContentHashtags::create("PaleoRecipes", "Paleo Recipes");
ContentHashtags::create("VeganRecipes", "Vegan Recipes");
ContentHashtags::create("VegetarianRecipes", "Vegetarian Recipes");
ContentHashtags::create("Appetizers", "Appetizer");
ContentHashtags::create("Breakfast", "Breakfast");
ContentHashtags::create("Dessert", "Dessert");
ContentHashtags::create("Drink", "Drink");
ContentHashtags::create("MainCourse", "Main Course");
ContentHashtags::create("Salad", "Salad");
ContentHashtags::create("Sandwich", "Sandwich");
ContentHashtags::create("Sides", "Sides");
ContentHashtags::create("Soup", "Soup and Stew");
ContentHashtags::create("BeefRecipes", "Beef");
ContentHashtags::create("CheeseRecipes", "Cheese");
ContentHashtags::create("ChickenRecipes", "Chicken");
ContentHashtags::create("DuckRecipes", "Duck");
ContentHashtags::create("EggRecipes", "Egg");
ContentHashtags::create("FishRecipes", "Fish");
ContentHashtags::create("LambRecipes", "Lamb");
ContentHashtags::create("PastaRecipes", "Pasta");
ContentHashtags::create("PorkRecipes", "Pork");
ContentHashtags::create("RiceRecipes", "Rice");
ContentHashtags::create("SeafoodRecipes", "Seafood");
ContentHashtags::create("TurkeyRecipes", "Turkey");
ContentHashtags::create("VegetableRecipes", "Vegetables");
ContentHashtags::create("ChristmasRecipes", "Christmas");
ContentHashtags::create("HalloweenRecipes", "Halloween");
ContentHashtags::create("EasterRecipes", "Easter");
ContentHashtags::create("ThanksgivingRecipes", "Thanksgiving");
ContentHashtags::create("PassoverRecipes", "Passover");
ContentHashtags::create("AmericanCuisine", "American Cuisine");
ContentHashtags::create("CajunCuisine", "Cajun Cuisine");
ContentHashtags::create("ChineseCuisine", "Chinese Cuisine");
ContentHashtags::create("FrenchCuisine", "French Cuisine");
ContentHashtags::create("GermanCuisine", "German Cuisine");
ContentHashtags::create("IndianCuisine", "Indian Cuisine");
ContentHashtags::create("ItalianCuisine", "Italian Cuisine");
ContentHashtags::create("JapaneseCuisine", "Japanese Cuisine");
ContentHashtags::create("MexicanCuisine", "Mexican Cuisine");
ContentHashtags::create("BakedGoods", "Baked Goods");
ContentHashtags::create("BarFood", "Bar Food");
ContentHashtags::create("BBQRecipes", "BBQ");
ContentHashtags::create("Cakes", "Cakes");
ContentHashtags::create("Candy", "Candy");
ContentHashtags::create("CasseroleRecipes", "Casserole");
ContentHashtags::create("CondimentRecipes", "Condiment");
ContentHashtags::create("Cookies", "Cookies");
ContentHashtags::create("DeepFriedRecipes", "Deep Fried");
ContentHashtags::create("Dips", "Dips");
ContentHashtags::create("GrillRecipes", "Grill");
ContentHashtags::create("JamRecipes", "Jams");
ContentHashtags::create("JellyRecipes", "Jellies");
ContentHashtags::create("PaniniRecipes", "Panini");
ContentHashtags::create("SalsaRecipes", "Salsa");
ContentHashtags::create("SauceRecipes", "Sauce");
ContentHashtags::create("StirFryRecipes", "Stir-Fry");
ContentHashtags::create("TexMexCuisine", "TexMex");
ContentHashtags::create("PersianCuisine", "Persian Cuisine");
ContentHashtags::create("SouthernCuisine", "Southern Cuisine");
ContentHashtags::create("MediterraneanCuisine", "Mediterranean Cuisine");