<?php if(!defined("CONF_PATH")) { die("No direct script access allowed."); } 

Database::initRoot();

// Create the Site's Official Hashtags
ContentHashtags::create("Sports", "Sports");
ContentHashtags::create("Hockey", "Hockey");
ContentHashtags::create("NCAAH", "NCAA Hockey");
ContentHashtags::create("AtlanticHockey", "Atlantic Hockey Conference");
ContentHashtags::create("AirForceHockey", "Air Force Falcons");
ContentHashtags::create("AmIntlHockey", "American International Yellow Jackets");
ContentHashtags::create("ArmyHockey", "Army Black Knights");
ContentHashtags::create("BentelyHockey", "Bentley Falcons");
ContentHashtags::create("CanisiusHockey", "Canisius Golden Griffins");
ContentHashtags::create("HolyCrossHockey", "Holy Cross Crusaders");
ContentHashtags::create("MercyhurstHockey", "Mercyhurst Lakers");
ContentHashtags::create("NiagraHockey", "Niagara Purple Eagles");
ContentHashtags::create("RobertMorrisHockey", "Robert Morris Colonials");
ContentHashtags::create("RochesterTechHockey", "Rochester Tech Tigers");
ContentHashtags::create("SacredHeartHockey", "Sacred Heart Pioneers");
ContentHashtags::create("BigTenHockey", "Big Ten Hockey");
ContentHashtags::create("MichiganHockey", "Michigan Wolverines");
ContentHashtags::create("MichStateHockey", "Michigan State Spartans");
ContentHashtags::create("MinnesotaHockey", "Minnesota Golden Gophers");
ContentHashtags::create("OhioStHockey", "Ohio State Buckeyes");
ContentHashtags::create("PennStateHockey", "Penn State Nittany Lions");
ContentHashtags::create("WisconsinHockey", "Wisconsin Badgers");
ContentHashtags::create("ECACHockey", "Eastern College Athletic Conference Hockey");
ContentHashtags::create("BrownHockey", "Brown Bears");
ContentHashtags::create("ClarksonHockey", "Clarkson Golden Knights");
ContentHashtags::create("ColgateHockey", "Colgate Raiders");
ContentHashtags::create("CornellHockey", "Cornell Big Red");
ContentHashtags::create("DartmouthHockey", "Dartmouth Big Green");
ContentHashtags::create("HarvardHockey", "Harvard Crimson");
ContentHashtags::create("PrincetonHockey", "Princeton Tigers");
ContentHashtags::create("QuinnipacHockey", "Quinnipac Bobcats");
ContentHashtags::create("RensselaerPolyHockey", "Rensselaer Poly Engineers");
ContentHashtags::create("StLawrenceHockey", "St. Lawrence Saints");
ContentHashtags::create("UnionHockey", "Union Dutchmen");
ContentHashtags::create("YaleHockey", "Yale Bulldogs");
ContentHashtags::create("HockeyEast", "Hockey East Conference");
ContentHashtags::create("BCEaglesHockey", "Boston College Eagles");
ContentHashtags::create("BostonUHockey", "Boston University Terriers");
ContentHashtags::create("UConnHockey", "Connecticut Huskies");
ContentHashtags::create("MaineHockey", "Maine Black Bears");
ContentHashtags::create("UMassAmHockey", "UMass-Amherst Minutemen");
ContentHashtags::create("UMassLowHockey", "UMass-Lowell River Hawks");
ContentHashtags::create("NHWildcatHockey", "New Hampshire Wildcats");
ContentHashtags::create("NEHuskiesHockey", "Northeastern Huskies");
ContentHashtags::create("NotreDameHockey", "Notre Dame Fighting Irish");
ContentHashtags::create("ProvidenceHockey", "Providence Friars");
ContentHashtags::create("VermontHockey", "Vermont Catamounts");
ContentHashtags::create("NCHC", "National Collegiate Hockey Conference");
ContentHashtags::create("COCollegeHockey", "Colorado College Tigers");
ContentHashtags::create("DenverHockey", "Denver Pioneers");
ContentHashtags::create("RedHawksHockey", "Miami (OH) RedHawks");
ContentHashtags::create("MNDuluthHockey", "Minnesota-Duluth Bulldogs");
ContentHashtags::create("NEBOmahaHockey", "Nebraska-Omaha Mavericks");
ContentHashtags::create("NDHockey", "North Dakota");
ContentHashtags::create("StCloudHockey", "St. Cloud Huskies");
ContentHashtags::create("WMUBroncosHockey", "Western Michigan Broncos");
ContentHashtags::create("WCHA", "Western Collegiate Hockey Association");
ContentHashtags::create("AHChargersHockey", "Alabama-Huntsville Chargers");
ContentHashtags::create("AASeawolvesHockey", "Alaska-Anchorage Seawolves");
ContentHashtags::create("AFNanooksHockey", "Alaska-Fairbanks Nanooks");
ContentHashtags::create("BemidjiStHockey", "Bemidji State Beavers");
ContentHashtags::create("BowlingGreenHockey", "Bowling Green Falcons");
ContentHashtags::create("FerrisStHockey", "Ferris State Bulldogs");
ContentHashtags::create("LakeSuperiorHockey", "Lake Superior Lakers");
ContentHashtags::create("MichTechHockey", "Michigan Tech Huskies");
ContentHashtags::create("MNStHockey", "Minnesota State Mavericks");
ContentHashtags::create("NMichHockey", "Northern Michigan Wildcats");