<?php if(!defined("CONF_PATH")) { die("No direct script access allowed."); } 

Database::initRoot();

// Create the Site's Official Hashtags
ContentHashtags::create("Music", "Music");
ContentHashtags::create("BluegrassMusic", "Bluegrass Music");
ContentHashtags::create("BluesMusic", "Blues Music");
ContentHashtags::create("ChristianMusic", "Christian Music");
ContentHashtags::create("ClassicalMusic", "Classical Music");
ContentHashtags::create("ComedyAudio", "Comedy Audio");
ContentHashtags::create("CountryMusic", "Country Music");
ContentHashtags::create("DanceMusic", "Dance (EDM) Music");
ContentHashtags::create("EasyListening", "Easy Listening");
ContentHashtags::create("ElectronicMusic", "Electronic Music");
ContentHashtags::create("FolkMusic", "Folk Music");
ContentHashtags::create("GospelMusic", "Gospel Music");
ContentHashtags::create("HardRockMusic", "Hard Rock Music");
ContentHashtags::create("HipHopMusic", "Hip-Hop Music");
ContentHashtags::create("HolidayMusic", "Holiday Music");
ContentHashtags::create("IndieMusic", "Indie Music");
ContentHashtags::create("InstrumentalMusic", "Instrumental Music");
ContentHashtags::create("JazzMusic", "Jazz Music");
ContentHashtags::create("LatinoMusic", "Latino Music");
ContentHashtags::create("MetalMusic", "Metal Music");
ContentHashtags::create("MusicalsMusic", "Musicals Music");
ContentHashtags::create("NewWaveMusic", "New Wave Music");
ContentHashtags::create("PopMusic", "Pop Music");
ContentHashtags::create("PunkMusic", "Punk Music");
ContentHashtags::create("RBMusic", "R&B Music");
ContentHashtags::create("RapMusic", "Rap Music");
ContentHashtags::create("ReggaeMusic", "Reggae Music");
ContentHashtags::create("RockNRollMusic", "Rock & Rol lMusic");
ContentHashtags::create("SongwriterMusic", "Singer/Songwriter Music");
ContentHashtags::create("SoulMusic", "Soul Music");
ContentHashtags::create("SountrackMusic", "Sountrack Music");
ContentHashtags::create("VocalMusic", "Vocal Music");

// Create the Site's Search Filters
ModuleSearch::createFilterOption("search-home", "Genres", "BluegrassMusic", "Bluegrass", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "BluesMusic", "Blues", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "ChristianMusic", "Christian", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "ClassicalMusic", "Classical", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "ComedyAudio", "Comedy", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "CountryMusic", "Country", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "DanceMusic", "Dance", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "EasyListening", "Easy Listening", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "ElectronicMusic", "Electronic", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "FolkMusic", "Folk", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "GospelMusic", "Gospel", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "HardRockMusic", "Hard Rock", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "HipHopMusic", "Hip Hop", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "HolidayMusic", "Holiday", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "IndieMusic", "Indie", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "InstrumentalMusic", "Instrumental", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "JazzMusic", "Jazz", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "LatinoMusic", "Latino", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "MetalMusic", "Metal", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "MusicalsMusic", "Musicals", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "NewWaveMusic", "New Wave", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "PopMusic", "Pop", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "PunkMusic", "Punk", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "RBMusic", "R&B", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "RapMusic", "Rap", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "ReggaeMusic", "Reggae", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "RockNRollMusic", "Rock & Roll", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "SongwriterMusic", "Singer/Songwriter", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "SoulMusic", "Soul", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "SountrackMusic", "Soundtrack", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Genres", "VocalMusic", "Vocal", ModuleSearch::FILTER_SINGLE);