<?php if(!defined("CONF_PATH")) { die("No direct script access allowed."); } 

Database::initRoot();

// Create the Site's Official Hashtags
ContentHashtags::create("Sports", "Sports");
ContentHashtags::create("Football", "Football");
ContentHashtags::create("NCAAF", "NCAA Division 1 Football");
ContentHashtags::create("AACFootball", "AAC Football");
ContentHashtags::create("UCBearcatsFB", "Cincinnati Bearcats Football");
ContentHashtags::create("UConnFB", "Connecticut Huskies Football");
ContentHashtags::create("ECUPiratesFB", "East Carolina Pirates Football");
ContentHashtags::create("HOUCougarsFB", "Houston Cougars Football");
ContentHashtags::create("MEMTigersFB", "Memphis Tigers Football");
ContentHashtags::create("SMUMustangsFB", "SMU Mustangs Football");
ContentHashtags::create("USFBullsFB", "South Florida Bulls Football");
ContentHashtags::create("TempleFB", "Temple Owls Football");
ContentHashtags::create("TulaneFB", "Tulane Green Wave Football");
ContentHashtags::create("TulsaFB", "Tulsa Golden Hurricanes Football");
ContentHashtags::create("UCFKnightsFB", "UCF Knights Football");
ContentHashtags::create("ACCFootball", "ACC Football");
ContentHashtags::create("BCEaglesFB", "Boston College Eagles Football");
ContentHashtags::create("ClemsonFB", "Clemson Tigers Football");
ContentHashtags::create("DukeFB", "Duke Blue Devils Football");
ContentHashtags::create("SeminoleFB", "Florida State Seminoles Football");
ContentHashtags::create("GATechFB", "Georgia Tech Yellow Jackets Football");
ContentHashtags::create("LouisvilleFB", "Louisville Cardinals Football");
ContentHashtags::create("UMiamiFB", "Miami (FL) Hurricanes Football");
ContentHashtags::create("TarHeelsFB", "North Carolina Tar Heels Football");
ContentHashtags::create("NCStateFB", "North Carolina State Wolfpack Football");
ContentHashtags::create("PittPantherFB", "Pittsburgh Panthers Football");
ContentHashtags::create("SyracuseFB", "Syracuse Orange Football");
ContentHashtags::create("UVCavaliersFB", "Virginia Cavaliers Football");
ContentHashtags::create("HokiesFB", "Virginia Tech Hokies Football");
ContentHashtags::create("WakeForestFB", "Wake Forest Demon Deacons Football");
ContentHashtags::create("Big12Football", "Big 12 Football");
ContentHashtags::create("BaylorFB", "Baylor Bears Football");
ContentHashtags::create("IowaStFB", "Iowa State Cyclones Football");
ContentHashtags::create("KansasFB", "Kansas Jayhawks Football");
ContentHashtags::create("KStateFB", "Kansas State Wildcats Football");
ContentHashtags::create("SoonersFB", "Oklahoma Sooners Football");
ContentHashtags::create("OKStateFB", "Oklahoma State Cowboys Football");
ContentHashtags::create("HornedFrogsFB", "TCU Horned Frogs Football");
ContentHashtags::create("TexasFB", "Texas Longhorns Football");
ContentHashtags::create("TexasTechFB", "Texas Tech Red Raiders Football");
ContentHashtags::create("WestVirginiaFB", "West Virginia Mountaineers Football");
ContentHashtags::create("BigTenFootball", "Big Ten Football");
ContentHashtags::create("IllinoisFB", "Illinois Fighting Illini Football");
ContentHashtags::create("IndianaFB", "Indiana Hoosiers Football");
ContentHashtags::create("IowaFB", "Iowa Hawkeyes Football");
ContentHashtags::create("MarylandFB", "Maryland Terrapins Football");
ContentHashtags::create("MichiganFB", "Michigan Wolverines Football");
ContentHashtags::create("MichStateFB", "Michigan State Spartans Football");
ContentHashtags::create("MinnesotaFB", "Minnesota Golden Gophers Football");
ContentHashtags::create("NebraskaFB", "Nebraska Cornhuskers Football");
ContentHashtags::create("NWWildcatsFB", "Northwester Wildcats Football");
ContentHashtags::create("OhioStFB", "Ohio State Buckeyes Football");
ContentHashtags::create("PennStateFB", "Penn State Nittany Lions Football");
ContentHashtags::create("PurdueFB", "Purdue Boilermakers Football");
ContentHashtags::create("RutgersFB", "Rutgers Scarlet Knights Football");
ContentHashtags::create("WisconsinFB", "Wisconsin Badgers Football");
ContentHashtags::create("ConferenceUSAFootball", "Conference USA Football");
ContentHashtags::create("FAUOwlsFB", "Florida Atlantic Owls Football");
ContentHashtags::create("FIUPanthersFB", "Florida International Panthers Football");
ContentHashtags::create("LATechFB", "Louisiana Tech Bulldogs Football");
ContentHashtags::create("MarshallFB", "Marshall Thundering Herd Football");
ContentHashtags::create("BlueRaidersFB", "Middle Tennessee Blue Raiders Football");
ContentHashtags::create("MeanGreenFB", "North Texas Mean Green Football");
ContentHashtags::create("OldDominionFB", "Old Dominion Monarchs Football");
ContentHashtags::create("RiceFB", "Rice Owls Football");
ContentHashtags::create("SouthernMissFB", "Southern Miss Golden Eagles Football");
ContentHashtags::create("UABBlazersFB", "UAB Blazers Football");
ContentHashtags::create("UTEPMinersFB", "UTEP Miners Football");
ContentHashtags::create("UTSARoadrunnersFB", "UTSA Roadrunners Football");
ContentHashtags::create("HilltoppersFB", "Western Kentucky Hilltoppers Football");
ContentHashtags::create("IndependentFootball", "Independent Football");
ContentHashtags::create("ArmyFB", "Army Black Knights Football");
ContentHashtags::create("BYUCougarFB", "Brigham Young Cougars Football");
ContentHashtags::create("NavyFB", "Navy Midshipmen Football");
ContentHashtags::create("NotreDameFB", "Notre Dame Fighting Irish Football");
ContentHashtags::create("MACFootball", "MAC Football");
ContentHashtags::create("AkronFB", "Akron Zips Football");
ContentHashtags::create("BallStFB", "Ball State Cardinals Football");
ContentHashtags::create("BowlingGreenFB", "Bowling Green Falcons Football");
ContentHashtags::create("BuffaloFB", "Buffalo Bulls Football");
ContentHashtags::create("CMUChipsFB", "Central Michigan Chippewas Football");
ContentHashtags::create("EMUEaglesFB", "Eastern Micigan Eagles Football");
ContentHashtags::create("KentStFB", "Kent State Golden Flashes Football");
ContentHashtags::create("UMassFB", "Massachusetts Minutemen Football");
ContentHashtags::create("MiamiOhioFB", "Miami (OH) Redhawks Football");
ContentHashtags::create("NIUHuskiesFB", "Northern Illinois Huskies Football");
ContentHashtags::create("OhioFB", "Ohio Bobcats Football");
ContentHashtags::create("ToledoFB", "Toledo Rockets Football");
ContentHashtags::create("WMUBroncosFB", "Western Michigan Broncos Football");
ContentHashtags::create("MountainWestFootball", "Mountain West Football");
ContentHashtags::create("AirForceFB", "Air Force Falcons Football");
ContentHashtags::create("BoiseStFB", "Boise State Broncos Football");
ContentHashtags::create("ColoradoStFB", "Colorado State Rams Football");
ContentHashtags::create("FresnoFB", "Fresno State Bulldogs Football");
ContentHashtags::create("HawaiiFB", "Hawaii Warriors Football");
ContentHashtags::create("NevadaFB", "Nevada Wolf Pack Football");
ContentHashtags::create("NewMexicoFB", "New Mexico Lobos Football");
ContentHashtags::create("SanDiegoStFB", "San Diego State Aztecs Football");
ContentHashtags::create("SanJoseStFB", "San Jose State Spartans Football");
ContentHashtags::create("UNLVRebelsFB", "UNLV Rebels Football");
ContentHashtags::create("UtahStFB", "Utah State Aggies Football");
ContentHashtags::create("WyomingFB", "Wyoming Cowboys Football");
ContentHashtags::create("Pac12Football", "Pac-12 Football");
ContentHashtags::create("ArizonaFB", "Arizona Wildcats Football");
ContentHashtags::create("ArizonStFB", "Arizona State Sun Devils Football");
ContentHashtags::create("CalBearsFB", "California Bears Football");
ContentHashtags::create("ColoradoFB", "Colorado Buffaloes Football");
ContentHashtags::create("OreganFB", "Oregon Ducks Football");
ContentHashtags::create("OregonStFB", "Oregon State Beavers Football");
ContentHashtags::create("StanfordFB", "Stanford Cardinal Football");
ContentHashtags::create("UCLABruinsFB", "UCLA Bruins Football");
ContentHashtags::create("TrojansFB", "USC Trojans Football");
ContentHashtags::create("UtahFB", "Utah Utes Football");
ContentHashtags::create("WashingtonFB", "Washington Huskies Football");
ContentHashtags::create("WashingtonStFB", "Washington State Cougars Football");
ContentHashtags::create("SECFootball", "SEC Football");
ContentHashtags::create("AlabamaFB", "Alabama Crimson Tide Football");
ContentHashtags::create("ArkansasFB", "Arkansas Razorbacks Football");
ContentHashtags::create("AuburnFB", "Auburn Tigers Football");
ContentHashtags::create("FloridaFB", "Florida Gators Football");
ContentHashtags::create("GeorgiaFB", "Georgia Bulldogs Football");
ContentHashtags::create("KentuckyFB", "Kentucky Wildcats Football");
ContentHashtags::create("LSUTigersFB", "LSU Tigers Football");
ContentHashtags::create("OleMissFB", "Mississippi Rebels Football");
ContentHashtags::create("MudDogsFB", "Mississippi State Mud Dogs Football");
ContentHashtags::create("MissouriFB", "Missouri Tigers Football");
ContentHashtags::create("SouthCarolinaFB", "South Carolina Gamecocks Football");
ContentHashtags::create("TennesseeFB", "Tennessee Volunteers Football");
ContentHashtags::create("AggiesFB", "Texas A&M Aggies Football");
ContentHashtags::create("VanderbiltFB", "Vanderbilt Commodores Football");
ContentHashtags::create("SunBeltFootball", "Sun Belt Football");
ContentHashtags::create("AppStFB", "Appalachian State Mountaineers Football");
ContentHashtags::create("ArkStFB", "Arkansas State Red Wolves Football");
ContentHashtags::create("GASouthernFB", "Georgia Southern Eagles Football");
ContentHashtags::create("GAStFB", "Georgia State Panthers Football");
ContentHashtags::create("IdahoFB", "Idaho Vandals Football");
ContentHashtags::create("RaginCajunsFB", "Louisiana-Lafayette Ragin' Cajuns Football");
ContentHashtags::create("WarhawksFB", "Louisiana-Monroe Warhawks Football");
ContentHashtags::create("NMStFB", "New Mexico State Aggies Football");
ContentHashtags::create("SouthAlabamaFB", "South Alabama Jaguars Football");
ContentHashtags::create("TexasStFB", "Texas State Bobcats Football");
ContentHashtags::create("TroyFB", "Troy Trojans Football");