<?php if(!defined("CONF_PATH")) { die("No direct script access allowed."); } 

Database::initRoot();

// Create the Site's Official Hashtags
ContentHashtags::create("Sports", "Sports");
ContentHashtags::create("ActionSports", "Action Sports");
ContentHashtags::create("BMX", "BMX");
ContentHashtags::create("BASEJumping", "BASE jumping");
ContentHashtags::create("CaveDiving", "Cave diving");
ContentHashtags::create("Caving", "Caving");
ContentHashtags::create("Freediving", "Freediving");
ContentHashtags::create("Freeflying", "Freeflying");
ContentHashtags::create("FreestyleScootering", "Freestyle scootering");
ContentHashtags::create("Freeskiing", "Freeskiing");
ContentHashtags::create("HangGliding", "Hang gliding");
ContentHashtags::create("IceClimbing", "Ice climbing");
ContentHashtags::create("IceCanoeing", "Ice canoeing");
ContentHashtags::create("Kitesurfing", "Kitesurfing");
ContentHashtags::create("LandWindsurfing", "Land windsurfing");
ContentHashtags::create("Longboarding", "Longboarding");
ContentHashtags::create("Motocross", "Motocross");
ContentHashtags::create("MountainBiking", "Mountain biking");
ContentHashtags::create("MountainBoarding", "Mountain boarding");
ContentHashtags::create("Paintballing", "Paintballing");
ContentHashtags::create("Paragliding", "Paragliding");
ContentHashtags::create("Parkour", "Parkour");
ContentHashtags::create("RallyRacing", "Rally racing");
ContentHashtags::create("Rafting", "Rafting");
ContentHashtags::create("RockClimbing", "Rock climbing");
ContentHashtags::create("Sandboarding", "Sandboarding");
ContentHashtags::create("ScubaDiving", "Scuba diving");
ContentHashtags::create("Skateboarding", "Skateboarding");
ContentHashtags::create("Skydiving", "Skydiving");
ContentHashtags::create("Skimboarding", "Skimboarding");
ContentHashtags::create("Snowboarding", "Snowboarding");
ContentHashtags::create("Snowmobiling", "Snowmobiling");
ContentHashtags::create("Snowskating", "Snowskating");
ContentHashtags::create("Skiing", "Skiing");
ContentHashtags::create("StreetLuging", "Street luging");
ContentHashtags::create("Surfing", "Surfing");
ContentHashtags::create("Wakeboarding", "Wakeboarding");
ContentHashtags::create("Waterskiing", "Waterskiing");
ContentHashtags::create("Waveski", "Waveski");
ContentHashtags::create("WhitewaterKayaking", "Whitewater kayaking");
ContentHashtags::create("Windsurfing", "Windsurfing");
ContentHashtags::create("WingsuitFlying", "Wingsuit flying");
ContentHashtags::create("Xpogoing", "Xpogoing");


// Create the Site's Search Filters
ModuleSearch::createFilterOption("search-home", "Action Sports", "BMX", "BMX", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "BASEJumping", "BASE jumping", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "CaveDiving", "Cave diving", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Caving", "Caving", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Freediving", "Freediving", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Freeflying", "Freeflying", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "FreestyleScootering", "Freestyle scootering", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Freeskiing", "Freeskiing", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "HangGliding", "Hang gliding", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "IceClimbing", "Ice climbing", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "IceCanoeing", "Ice canoeing", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Kitesurfing", "Kitesurfing", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "LandWindsurfing", "Land windsurfing", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Longboarding", "Longboarding", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Motocross", "Motocross", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "MountainBiking", "Mountain biking", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "MountainBoarding", "Mountain boarding", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Paintballing", "Paintballing", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Paragliding", "Paragliding", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Parkour", "Parkour", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "RallyRacing", "Rally racing", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Rafting", "Rafting", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "RockClimbing", "Rock climbing", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Sandboarding", "Sandboarding", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "ScubaDiving", "Scuba diving", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Skateboarding", "Skateboarding", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Skydiving", "Skydiving", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Skimboarding", "Skimboarding", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Snowboarding", "Snowboarding", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Snowmobiling", "Snowmobiling", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Snowskating", "Snowskating", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Skiing", "Skiing", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "StreetLuging", "Street luging", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Surfing", "Surfing", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Wakeboarding", "Wakeboarding", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Waterskiing", "Waterskiing", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Waveski", "Waveski", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "WhitewaterKayaking", "Whitewater kayaking", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Windsurfing", "Windsurfing", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "WingsuitFlying", "Wingsuit flying", ModuleSearch::FILTER_SINGLE);
ModuleSearch::createFilterOption("search-home", "Action Sports", "Xpogoing", "Xpogoing", ModuleSearch::FILTER_SINGLE);