<?php if(!defined("CONF_PATH")) { die("No direct script access allowed."); } 

Database::initRoot();

// Create the Site's Official Hashtags
ContentHashtags::create("Fashion", "Fashion");
ContentHashtags::create("Accessories", "Fashion Accessories");
ContentHashtags::create("AccessoryDesigners", "Accessory Designers");
ContentHashtags::create("Bags", "Bags");
ContentHashtags::create("Belts", "Belts");
ContentHashtags::create("Clutches", "Clutches");
ContentHashtags::create("Eyewear", "Eyewear");
ContentHashtags::create("Gloves", "Gloves");
ContentHashtags::create("Hats", "Hats");
ContentHashtags::create("Jewelry", "Jewelry");
ContentHashtags::create("Scarves", "Scarves");
ContentHashtags::create("Totes", "Totes");
ContentHashtags::create("Beauty", "Beauty");
ContentHashtags::create("BeautyBrands", "Beauty Brands");
ContentHashtags::create("BodyCare", "Body Care");
ContentHashtags::create("Fragrances", "Fragrances");
ContentHashtags::create("HairCare", "Hair Care");
ContentHashtags::create("Makeup", "Makeup");
ContentHashtags::create("SkinCare", "SkinCare");
ContentHashtags::create("Clothing", "Clothing");
ContentHashtags::create("BridalFashion", "Bridal");
ContentHashtags::create("CoutureFashion", "Couture");
ContentHashtags::create("Denim", "Denim");
ContentHashtags::create("DesignerFashion", "Clothing Designers");
ContentHashtags::create("Intimates", "Intimates");
ContentHashtags::create("PreFallFashion", "Pre-Fall");
ContentHashtags::create("ReadyToWear", "Ready-to-Wear");
ContentHashtags::create("ResortFashion", "Resort");
ContentHashtags::create("RunwayFashion", "Runway");
ContentHashtags::create("Sportswear", "Sportswear");
ContentHashtags::create("Swimwear", "Swimwear");
ContentHashtags::create("FashionLabels", "Labels");
ContentHashtags::create("FashionNews", "Fashion News");
ContentHashtags::create("FashionEvents", "Fashion Events");
ContentHashtags::create("BerlinFashionWeek", "Berlin Fashion Week");
ContentHashtags::create("BonnarooFashion", "Bonnaroo Fashion");
ContentHashtags::create("CoachellaFashion", "Coachella Fashion");
ContentHashtags::create("CopenhagenFashionWeek", "Copenhagen Fashion Week");
ContentHashtags::create("LollapaloozaFashion", "Lollapalooza Fashion");
ContentHashtags::create("LondonFashionWeek", "London Fashion Week");
ContentHashtags::create("LAFashionWeek", "Los Angeles Fashion Week");
ContentHashtags::create("MadridFashionWeek", "Madrid Fashion Week");
ContentHashtags::create("MilanFashionWeek", "Milan Fashion Week");
ContentHashtags::create("NYCFashionWeek", "New York Fashion Week");
ContentHashtags::create("ParisFashionWeek", "Paris Fashion Week");
ContentHashtags::create("SundanceFashion", "Sundance Fashion");
ContentHashtags::create("SXSWFashion", "SXSW Fashion");
ContentHashtags::create("TokyoFashionWeek", "Tokyo Fashion Week");
ContentHashtags::create("Footwear", "Footwear");
ContentHashtags::create("AthleticShoes", "Athletic Shoes");
ContentHashtags::create("BoatShoes", "Boat Shoes");
ContentHashtags::create("Boots", "Boots");
ContentHashtags::create("Clogs", "Clogs");
ContentHashtags::create("DressBoots", "DressBoots");
ContentHashtags::create("DressShoes", "DressShoes");
ContentHashtags::create("Flats", "Flats");
ContentHashtags::create("Heels", "Heels");
ContentHashtags::create("MulesShoes", "Mules");
ContentHashtags::create("PlatformBoots", "Platform Boots");
ContentHashtags::create("PlatformShoes", "Platform Shoes");
ContentHashtags::create("PumpShoes", "Pumps");
ContentHashtags::create("Sandals", "Sandals");
ContentHashtags::create("Slingbacks", "Slingbacks");
ContentHashtags::create("SlipOns", "Slip-Ons");
ContentHashtags::create("Slippers", "Slippers");
ContentHashtags::create("FashionStyles", "Fashion Styles");
ContentHashtags::create("FashionTips", "Fashion Tips");